apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: php-s2i-ci-pipeline
spec:
  params:
    - name: APP_GIT_URL
      type: string

    - name: APP_GIT_REVISION
      type: string
      default: main

    - name: MANIFEST_GIT_URL
      type: string

    - name: MANIFEST_GIT_REVISION
      type: string
      default: main

    - name: IMAGE_REGISTRY
      type: string
      default: quay.io

    - name: IMAGE_ORG
      type: string

    - name: IMAGE_NAME
      type: string

    - name: S2I_BUILDER_IMAGE
      type: string
      default: registry.redhat.io/rhscl/php-74-rhel7

    - name: MANIFEST_FILE
      type: string
      default: deployment.yaml

    - name: IMAGE_YAML_PATH
      type: string
      default: .spec.template.spec.containers[0].image

  workspaces:
    - name: source
    - name: manifest

  tasks:
    - name: clone-app
      taskRef:
        apiVersion: tekton.dev/v1
        kind: ClusterTask
        name: git-clone
      params:
        - name: url
          value: $(params.APP_GIT_URL)
        - name: revision
          value: $(params.APP_GIT_REVISION)
      workspaces:
        - name: output
          workspace: source

    - name: generate-tag
      runAfter:
        - clone-app
      taskRef:
        apiVersion: tekton.dev/v1
        name: generate-image-tag

    - name: s2i-build
      runAfter:
        - generate-tag
      taskRef:
        apiVersion: tekton.dev/v1
        kind: ClusterTask
        name: s2i
      params:
        - name: IMAGE
          value: $(params.IMAGE_REGISTRY)/$(params.IMAGE_ORG)/$(params.IMAGE_NAME):$(tasks.generate-tag.results.image-tag)
        - name: BUILDER_IMAGE
          value: $(params.S2I_BUILDER_IMAGE)
      workspaces:
        - name: source
          workspace: source

    - name: scan-image
      runAfter:
        - s2i-build
      taskRef:
        apiVersion: tekton.dev/v1
        name: trivy-image-scan
      params:
        - name: IMAGE
          value: $(params.IMAGE_REGISTRY)/$(params.IMAGE_ORG)/$(params.IMAGE_NAME):$(tasks.generate-tag.results.image-tag)

    - name: clone-manifest
      runAfter:
        - scan-image
      taskRef:
        apiVersion: tekton.dev/v1
        kind: ClusterTask
        name: git-clone
      params:
        - name: url
          value: $(params.MANIFEST_GIT_URL)
        - name: revision
          value: $(params.MANIFEST_GIT_REVISION)
      workspaces:
        - name: output
          workspace: manifest

    - name: update-manifest
      runAfter:
        - clone-manifest
      taskRef:
        apiVersion: tekton.dev/v1
        name: update-manifest-repo
      params:
        - name: IMAGE
          value: $(params.IMAGE_REGISTRY)/$(params.IMAGE_ORG)/$(params.IMAGE_NAME):$(tasks.generate-tag.results.image-tag)
        - name: MANIFEST_FILE
          value: $(params.MANIFEST_FILE)
        - name: IMAGE_YAML_PATH
          value: $(params.IMAGE_YAML_PATH)
      workspaces:
        - name: manifest
          workspace: manifest
